'use client';

/**
 * Sprint 16 — quick-fill panel for the product form. Collapsed by default;
 * power users expand it, paste a JSON blob (typically generated by ChatGPT
 * from the `Copy ChatGPT prompt` button below), and click Apply to populate
 * every form field in one shot. The Server Action that saves the product is
 * untouched — Apply only mutates client state, so the user can still review,
 * tweak, and click Save themselves. Images + compatibility pickers remain
 * separate (those need real uploads / multi-select; out of scope here).
 *
 * Brand + category accept a name (AR or EN), a slug, or a cuid. Resolution
 * order: id > slug > nameAr exact > nameEn case-insensitive. On miss we
 * surface up to 5 suggestions so the user can pick the right spelling.
 *
 * A `window.__pbfFillProduct(json)` escape hatch is exposed so the user can
 * trigger Apply from DevTools (useful for scripting bulk paste).
 */

import { useEffect, useId, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import type { ResolveItem } from '@/lib/catalog/admin-options';

export type ProductPasteApplied = {
  sku?: string;
  brandId?: string;
  categoryId?: string;
  slug?: string;
  nameAr?: string;
  nameEn?: string;
  descriptionAr?: string;
  descriptionEn?: string;
  basePriceEgp?: number;
  vatExempt?: boolean;
  returnable?: boolean;
  authenticity?: 'GENUINE' | 'COMPATIBLE';
  condition?: 'NEW' | 'USED';
  warranty?: string;
  conditionNote?: string;
  status?: 'ACTIVE' | 'ARCHIVED';
  specs?: Record<string, string>;
  specsAr?: Record<string, string>;
  specsEn?: Record<string, string>;
};

export type PasteLabels = {
  title: string;
  hint: string;
  showHide: string;
  hide: string;
  textareaPlaceholder: string;
  apply: string;
  copyPrompt: string;
  copied: string;
  paste: string;
  clear: string;
  appliedFieldsHeader: string;
  errorsHeader: string;
  schemaHeader: string;
};

const SAMPLE_JSON = `{
  "sku": "BROTHER-DCP-T530DW",
  "brand": "Brother",
  "category": "Ink Tank Printers",
  "nameAr": "طابعة Brother DCP-T530DW لاسلكية ألوان متعددة الوظائف",
  "nameEn": "Brother DCP-T530DW Wireless Color Ink Tank All-in-One Printer",
  "descriptionAr": "طابعة Brother DCP-T530DW متعددة الوظائف (طباعة، نسخ، سكان) بنظام خزان حبر منخفض التكلفة.",
  "descriptionEn": "Brother DCP-T530DW is a wireless all-in-one color ink tank printer designed for cost-efficient, high-volume printing.",
  "basePriceEgp": 8200,
  "authenticity": "GENUINE",
  "condition": "NEW",
  "warranty": "ضمان سنة رسمي",
  "vatExempt": true,
  "returnable": true,
  "specsAr": {
    "النوع": "طابعة خزان حبر",
    "اللون": "ألوان",
    "الاتصال": "USB 2.0 + Wi-Fi"
  },
  "specsEn": {
    "Type": "Ink Tank Printer",
    "Color": "Color",
    "Connectivity": "USB 2.0 + Wi-Fi"
  },
  "status": "ACTIVE"
}`;

function buildPrompt(brands: ResolveItem[], categories: ResolveItem[]): string {
  const brandList = brands.map((b) => b.nameEn).join(' / ');
  const catList = categories
    .slice(0, 12)
    .map((c) => c.nameAr)
    .join(' / ');
  return `أنا هضيف منتج جديد في كتالوج Print By Falcon. طلعلي JSON واحد بالشكل ده بالظبط (مفيش كلام قبله أو بعده):

${SAMPLE_JSON}

قواعد:
- "brand" لازم يكون اسم من القايمة دي بالظبط: ${brandList || '— مفيش brands ظاهرة —'}
- "category" لازم يكون اسم تصنيف موجود مثل: ${catList || '— مفيش categories ظاهرة —'}
- "specsAr" و "specsEn" نفس عدد الـ keys ونفس الترتيب.
- الـ values نص عادي، مش markdown ولا روابط.
- "basePriceEgp" رقم بالجنيه المصري بدون فواصل.
- "authenticity": "GENUINE" للأصلي، "COMPATIBLE" للمتوافق.
- "condition": "NEW" أو "USED".
- "warranty" نص حر بالعربي مثل "ضمان سنة رسمي" / "بدون ضمان".
- لو معلومة مش متأكد منها سيبها فاضية ("") بدل ما تختلق.
- "status" دايماً "ACTIVE".

المنتج: [الصق هنا اسم المنتج أو لينك أو وصف]`;
}

function stripCodeFence(text: string): string {
  let t = text.trim();
  if (t.startsWith('﻿')) t = t.slice(1);
  t = t.replace(/^```(?:json|JSON|javascript|js)?\s*\n?/, '');
  t = t.replace(/\n?```\s*$/, '');
  return t.trim();
}

type ResolveResult =
  | { ok: true; id: string }
  | { ok: false; suggestions: string[] };

function resolveOption(raw: string, options: ResolveItem[]): ResolveResult {
  const v = raw.trim();
  if (!v) return { ok: false, suggestions: [] };
  const byId = options.find((o) => o.id === v);
  if (byId) return { ok: true, id: byId.id };
  const lower = v.toLowerCase();
  const bySlug = options.find((o) => o.slug.toLowerCase() === lower);
  if (bySlug) return { ok: true, id: bySlug.id };
  const byAr = options.find((o) => o.nameAr.trim() === v);
  if (byAr) return { ok: true, id: byAr.id };
  const byEnExact = options.find(
    (o) => o.nameEn.trim().toLowerCase() === lower,
  );
  if (byEnExact) return { ok: true, id: byEnExact.id };
  // suggestions: substring match in either name
  const subs = options
    .filter(
      (o) =>
        o.nameEn.toLowerCase().includes(lower) ||
        o.nameAr.includes(v) ||
        o.slug.toLowerCase().includes(lower),
    )
    .slice(0, 5)
    .map((o) => `${o.nameEn} / ${o.nameAr}`);
  return { ok: false, suggestions: subs };
}

function asString(v: unknown): string | undefined {
  return typeof v === 'string' ? v : undefined;
}
function asTrimmedString(v: unknown): string | undefined {
  if (typeof v !== 'string') return undefined;
  return v.trim();
}
function asBool(v: unknown): boolean | undefined {
  if (typeof v === 'boolean') return v;
  if (typeof v === 'string') {
    const t = v.trim().toLowerCase();
    if (t === 'true' || t === 'yes' || t === '1') return true;
    if (t === 'false' || t === 'no' || t === '0') return false;
  }
  return undefined;
}
function asNumber(v: unknown): number | undefined {
  if (typeof v === 'number' && Number.isFinite(v)) return v;
  if (typeof v === 'string' && v.trim()) {
    const n = Number(v.replace(/,/g, ''));
    if (Number.isFinite(n)) return n;
  }
  return undefined;
}
function asEnum<T extends string>(
  v: unknown,
  allowed: readonly T[],
): T | undefined {
  if (typeof v !== 'string') return undefined;
  const upper = v.trim().toUpperCase() as T;
  return (allowed as readonly string[]).includes(upper) ? upper : undefined;
}
function asStringRecord(v: unknown): Record<string, string> | undefined {
  if (!v || typeof v !== 'object' || Array.isArray(v)) return undefined;
  const out: Record<string, string> = {};
  for (const [k, val] of Object.entries(v as Record<string, unknown>)) {
    const key = k.trim();
    if (!key) continue;
    if (typeof val === 'string') {
      const trimmed = val.trim();
      if (trimmed) out[key] = trimmed;
    } else if (typeof val === 'number' || typeof val === 'boolean') {
      out[key] = String(val);
    }
  }
  return out;
}

export function ProductJsonPaste({
  brandsResolve,
  categoriesResolve,
  onApply,
  labels,
}: {
  brandsResolve: ResolveItem[];
  categoriesResolve: ResolveItem[];
  onApply: (patch: ProductPasteApplied) => void;
  labels: PasteLabels;
}) {
  const [open, setOpen] = useState(false);
  const [text, setText] = useState('');
  const [errors, setErrors] = useState<string[]>([]);
  const [appliedFields, setAppliedFields] = useState<string[]>([]);
  const [showSchema, setShowSchema] = useState(false);
  const [copied, setCopied] = useState(false);
  const fieldId = useId();
  const onApplyRef = useRef(onApply);
  onApplyRef.current = onApply;
  const brandsRef = useRef(brandsResolve);
  brandsRef.current = brandsResolve;
  const categoriesRef = useRef(categoriesResolve);
  categoriesRef.current = categoriesResolve;

  const apply = (raw: string): { errors: string[]; applied: string[] } => {
    const errs: string[] = [];
    const applied: string[] = [];
    const cleaned = stripCodeFence(raw);
    if (!cleaned) {
      errs.push('Empty input.');
      return { errors: errs, applied };
    }
    let parsed: unknown;
    try {
      parsed = JSON.parse(cleaned);
    } catch (e) {
      errs.push(`Invalid JSON: ${(e as Error).message}`);
      return { errors: errs, applied };
    }
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
      errs.push('JSON must be a single object.');
      return { errors: errs, applied };
    }
    const obj = parsed as Record<string, unknown>;
    const patch: ProductPasteApplied = {};

    // Brand: prefer explicit brandId, else free-form `brand`.
    const brandIdRaw = asTrimmedString(obj.brandId);
    const brandRaw = asTrimmedString(obj.brand);
    if (brandIdRaw) {
      const r = resolveOption(brandIdRaw, brandsRef.current);
      if (r.ok) {
        patch.brandId = r.id;
        applied.push('brand');
      } else {
        errs.push(`brandId "${brandIdRaw}" not found.`);
      }
    } else if (brandRaw) {
      const r = resolveOption(brandRaw, brandsRef.current);
      if (r.ok) {
        patch.brandId = r.id;
        applied.push('brand');
      } else {
        const hint = r.suggestions.length
          ? ` Suggestions: ${r.suggestions.join(' | ')}`
          : '';
        errs.push(`brand "${brandRaw}" not found.${hint}`);
      }
    }

    const categoryIdRaw = asTrimmedString(obj.categoryId);
    const categoryRaw = asTrimmedString(obj.category);
    if (categoryIdRaw) {
      const r = resolveOption(categoryIdRaw, categoriesRef.current);
      if (r.ok) {
        patch.categoryId = r.id;
        applied.push('category');
      } else {
        errs.push(`categoryId "${categoryIdRaw}" not found.`);
      }
    } else if (categoryRaw) {
      const r = resolveOption(categoryRaw, categoriesRef.current);
      if (r.ok) {
        patch.categoryId = r.id;
        applied.push('category');
      } else {
        const hint = r.suggestions.length
          ? ` Suggestions: ${r.suggestions.join(' | ')}`
          : '';
        errs.push(`category "${categoryRaw}" not found.${hint}`);
      }
    }

    const copyText = (k: keyof ProductPasteApplied, src: string) => {
      const v = asString(obj[src]);
      if (v !== undefined) {
        (patch as Record<string, unknown>)[k] = v;
        applied.push(src);
      }
    };
    copyText('sku', 'sku');
    copyText('slug', 'slug');
    copyText('nameAr', 'nameAr');
    copyText('nameEn', 'nameEn');
    copyText('descriptionAr', 'descriptionAr');
    copyText('descriptionEn', 'descriptionEn');
    copyText('warranty', 'warranty');
    copyText('conditionNote', 'conditionNote');

    const price = asNumber(obj.basePriceEgp);
    if (price !== undefined) {
      patch.basePriceEgp = price;
      applied.push('basePriceEgp');
    }
    const vat = asBool(obj.vatExempt);
    if (vat !== undefined) {
      patch.vatExempt = vat;
      applied.push('vatExempt');
    }
    const returnable = asBool(obj.returnable);
    if (returnable !== undefined) {
      patch.returnable = returnable;
      applied.push('returnable');
    }
    const auth = asEnum(obj.authenticity, ['GENUINE', 'COMPATIBLE'] as const);
    if (auth) {
      patch.authenticity = auth;
      applied.push('authenticity');
    }
    const cond = asEnum(obj.condition, ['NEW', 'USED'] as const);
    if (cond) {
      patch.condition = cond;
      applied.push('condition');
    }
    const status = asEnum(obj.status, ['ACTIVE', 'ARCHIVED'] as const);
    if (status) {
      patch.status = status;
      applied.push('status');
    }
    const specs = asStringRecord(obj.specs);
    if (specs) {
      patch.specs = specs;
      applied.push(`specs (${Object.keys(specs).length})`);
    }
    const specsAr = asStringRecord(obj.specsAr);
    if (specsAr) {
      patch.specsAr = specsAr;
      applied.push(`specsAr (${Object.keys(specsAr).length})`);
    }
    const specsEn = asStringRecord(obj.specsEn);
    if (specsEn) {
      patch.specsEn = specsEn;
      applied.push(`specsEn (${Object.keys(specsEn).length})`);
    }

    if (Object.keys(patch).length === 0) {
      errs.push('No recognised fields in JSON.');
      return { errors: errs, applied };
    }

    onApplyRef.current(patch);
    return { errors: errs, applied };
  };

  // Expose console helper. Returns a result object so the user can inspect
  // what was applied / what failed when running from DevTools.
  useEffect(() => {
    type Win = Window & {
      __pbfFillProduct?: (json: string) => {
        errors: string[];
        applied: string[];
      };
    };
    const w = window as Win;
    w.__pbfFillProduct = (json: string) => {
      const result = apply(json);
      setText(json);
      setErrors(result.errors);
      setAppliedFields(result.applied);
      setOpen(true);
      return result;
    };
    return () => {
      delete w.__pbfFillProduct;
    };
    // apply closes over refs (brands/categories/onApply), so it's stable.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleApply = () => {
    const result = apply(text);
    setErrors(result.errors);
    setAppliedFields(result.applied);
  };

  const handleClear = () => {
    setText('');
    setErrors([]);
    setAppliedFields([]);
  };

  const handlePaste = async () => {
    try {
      const clip = await navigator.clipboard.readText();
      if (clip) setText(clip);
    } catch {
      // clipboard read can fail on permission — ignore silently, user can
      // ctrl+v into the textarea directly.
    }
  };

  const handleCopyPrompt = async () => {
    const prompt = buildPrompt(brandsResolve, categoriesResolve);
    try {
      await navigator.clipboard.writeText(prompt);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // fall back: select textarea content so user can copy manually
      setText(prompt);
    }
  };

  return (
    <div className="rounded-md border border-dashed bg-muted/40 p-4">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="flex w-full items-center justify-between text-left text-sm font-medium"
        aria-expanded={open}
        aria-controls={fieldId}
      >
        <span>
          {open ? '▾' : '▸'} {labels.title}
        </span>
        <span className="text-xs text-muted-foreground">
          {open ? labels.hide : labels.showHide}
        </span>
      </button>
      {open ? (
        <div id={fieldId} className="mt-3 space-y-3">
          <p className="text-xs text-muted-foreground">{labels.hint}</p>
          <div className="flex flex-wrap gap-2">
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={handleCopyPrompt}
            >
              {copied ? labels.copied : labels.copyPrompt}
            </Button>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={handlePaste}
            >
              {labels.paste}
            </Button>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => setShowSchema((v) => !v)}
            >
              {labels.schemaHeader}
            </Button>
          </div>
          {showSchema ? (
            <pre className="max-h-72 overflow-auto rounded border bg-canvas p-3 text-[11px] leading-relaxed">
              {SAMPLE_JSON}
            </pre>
          ) : null}
          <Textarea
            rows={10}
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder={labels.textareaPlaceholder}
            className="font-mono text-xs"
            dir="ltr"
            spellCheck={false}
          />
          <div className="flex flex-wrap gap-2">
            <Button type="button" onClick={handleApply} disabled={!text.trim()}>
              {labels.apply}
            </Button>
            <Button
              type="button"
              variant="outline"
              onClick={handleClear}
              disabled={
                !text && appliedFields.length === 0 && errors.length === 0
              }
            >
              {labels.clear}
            </Button>
          </div>
          {appliedFields.length > 0 ? (
            <div className="rounded border border-emerald-500/40 bg-emerald-500/5 p-3 text-xs">
              <p className="mb-1 font-medium text-emerald-700 dark:text-emerald-400">
                {labels.appliedFieldsHeader}
              </p>
              <p className="text-muted-foreground">
                {appliedFields.join(' • ')}
              </p>
            </div>
          ) : null}
          {errors.length > 0 ? (
            <div className="rounded border border-destructive/40 bg-destructive/5 p-3 text-xs">
              <p className="mb-1 font-medium text-destructive">
                {labels.errorsHeader}
              </p>
              <ul className="list-disc space-y-0.5 ps-5 text-muted-foreground">
                {errors.map((e, i) => (
                  <li key={i}>{e}</li>
                ))}
              </ul>
            </div>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}
